made the tax config option optional for those not charging taxes

diff --git a/lib/clinvoice/generate-output b/lib/clinvoice/generate-output
--- a/lib/clinvoice/generate-output
+++ b/lib/clinvoice/generate-output
@@ -160,10 +160,13 @@ vars[totalhours]=
 vars[hourlyrate]=${conf[contract.hourly-rate]}
 
 local tax=${conf[contract.tax]}
-[[ $tax =~ "^([^ ]+)\s+([0-9.]+)%\s*$" ]] || die "invalid contract.tax format '$tax' (ex: VAT 5%)"
-vars[taxname]=${match[1]}
-vars[taxpercent]=${match[2]}
-vars[taxid]=${conf[contract.taxid]}
+if [[ -n "$tax" ]] ; then
+	[[ $tax =~ "^([^ ]+)\s+([0-9.]+)%\s*$" ]] || die "invalid contract.tax format '$tax' (ex: VAT 5%)"
+
+	vars[taxname]=${match[1]}
+	vars[taxpercent]=${match[2]}
+	vars[taxid]=${conf[contract.taxid]}
+fi
 
 for day in ${(k)dayhours} ; do
         local -F hours=${dayhours[$day]}
